num1 = float(input("si es categoria A: GANAS 1500")
num2 = float(input("si es categoria B: GANAS 2000")
num3 = float(input("si es categoria C: GANAS 2500")
if promedio = (num1 + num3)
else: print("raiz cuadrada")
